spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: inventory
    password: inventory
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080
